apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
spec:
  project: dynaflow
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mongodb
    targetRevision: 16.x.x
    helm:
      valuesObject:
        image:
          registry: ""
          repository: mongo
          tag: "7"
        auth:
          existingSecret: "mongodb-credentials"
          databases:
            - vehicle
          usernames:
            - dynaflow
        architecture: standalone
  destination:
    server: https://kubernetes.default.svc
    namespace: dynaflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
