apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-db
  namespace: argocd
spec:
  project: dynaflow
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 16.x.x
    helm:
      valuesObject:
        image:
          registry: ""
          repository: postgres
          tag: "16-alpine"
        auth:
          existingSecret: "postgres-credentials"
          database: "auth"
          username: "dynaflow"
        primary:
          initdb:
            scripts:
              init-dbs.sql: |
                CREATE DATABASE access;
                CREATE DATABASE site;
                GRANT ALL PRIVILEGES ON DATABASE access TO dynaflow;
                GRANT ALL PRIVILEGES ON DATABASE site TO dynaflow;
  destination:
    server: https://kubernetes.default.svc
    namespace: dynaflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
