apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: dynaflow
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: 21.x.x
    helm:
      valuesObject:
        image:
          registry: ""
          repository: redis
          tag: "7-alpine"
        auth:
          existingSecret: "redis-credentials"
          existingSecretPasswordKey: "redis-password"
        architecture: standalone
  destination:
    server: https://kubernetes.default.svc
    namespace: dynaflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
