apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dynaflow-services
  namespace: argocd
spec:
  project: dynaflow
  source:
    repoURL: https://github.com/radu-lzr/dynaflow
    targetRevision: argocd-conf
    path: argocd/definitions/dynaflow/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: dynaflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
