apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: monitoring
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: mimir-distributed
      targetRevision: 6.0.6
      helm:
        valueFiles:
          - $values/argocd/values/mimir.yaml
    - repoURL: https://github.com/radu-lzr/dynaflow
      targetRevision: main
      path: values
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/namespaceSelector/matchExpressions
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/namespaceSelector/matchExpressions
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true