apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: monitoring
  sources:
    - repoURL: [https://prometheus-community.github.io/helm-charts](https://prometheus-community.github.io/helm-charts)
      chart: kube-prometheus-stack
      targetRevision: 83.6.0
      helm:
        valueFiles:
          - $values/argocd/values/kube-prometheus-stack.yaml
    - repoURL: [https://github.com/radu-lzr/dynaflow](https://github.com/radu-lzr/dynaflow)
      targetRevision: main
      ref: values
  ignoreDifferences:
    - kind: Secret
      name: kube-prometheus-stack-grafana
      namespace: monitoring
      jsonPointers:
        - /data/admin-password
    - group: apps
      kind: Deployment
      name: kube-prometheus-stack-grafana
      namespace: monitoring
      jsonPointers:
        - /spec/template/metadata/annotations/checksum~1secret
  destination:
    server: [https://kubernetes.default.svc](https://kubernetes.default.svc)
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true